### ISSUE TITLE
Problems with Wi Fi

### ISSUE THREAD

**Issue by filkuzmanovski** [RanbirAulakh/Asus-Q501LA-Hackintosh#8]
I went over the installation today, all is well since I am using 10.10.4 I used https://github.com/gvkt/Asus-Q501LA-Hackintosh updates, but I am unable to get wi fi. It is only reading my ethernet. Also when I am unable to download anything from the App Store and I get this message "Your device or computer could not be verified. Contact support for assistance."
Any help is appreciated

**Comment by RanbirAulakh** [comment]
@filkuzmanovski What is your wifi card? The wifi card (Atheros AR9485) that came with the laptop will not work.

**Comment by filkuzmanovski** [comment]
@RanbirAulakh Thats the one I have. Which card should I buy that would run best with the current setup?

**Comment by RanbirAulakh** [comment]
@filkuzmanovski The wireless card I currently have is Atheros AR9285. However, that does not have the bluetooth feature. If you want the bluetooth feature in it, I would recommend checking this page; http://wiki.osx86project.org/wiki/index.php/HCL_10.8.2#Wireless and find any pci-e.

**Comment by filkuzmanovski** [comment]
Thank You
